# Generated by Django 4.2.29 on 2026-03-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_daily_analysis_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desired_job_direction',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='희망 방향'),
        ),
        migrations.AddField(
            model_name='user',
            name='desired_job_direction_other',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='기타 희망 방향'),
        ),
    ]
