# Generated by Django 4.2.29 on 2026-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='디스코드 ID'),
        ),
    ]
