from django.urls import path

from .views import (
    api_auto_checkout,
    api_bulk_checkin,
    api_cancel_attendance,
    api_cancel_delete,
    api_change_student_password,
    api_confirm_delete,
    api_edit_attendance,
    api_main,
    api_monthly_attendance_goals,
    api_monthly_stats,
    api_schedule_delete,
    api_set_location,
    api_student_detail,
    api_student_monthly_attendance,
    api_set_time,
    api_weekly_attendance,
    dashboard_change_password,
    dashboard_cancel_delete,
    dashboard_confirm_delete,
    dashboard_edit_attendance,
    dashboard_schedule_delete,
)

urlpatterns = [
    path("student/<str:student_id>/change-password/", dashboard_change_password, name="dashboard-change-password"),
    path("student/<str:student_id>/schedule-delete/", dashboard_schedule_delete, name="dashboard-schedule-delete"),
    path("student/<str:student_id>/cancel-delete/", dashboard_cancel_delete, name="dashboard-cancel-delete"),
    path("student/<str:student_id>/confirm-delete/", dashboard_confirm_delete, name="dashboard-confirm-delete"),
    path("api/main/", api_main, name="dashboard-api-main"),
    path("api/weekly/", api_weekly_attendance, name="dashboard-api-weekly"),
    path("api/auto-checkout/", api_auto_checkout, name="dashboard-api-auto-checkout"),
    path("api/bulk-checkin/", api_bulk_checkin, name="dashboard-api-bulk-checkin"),
    path("api/cancel-attendance/", api_cancel_attendance, name="dashboard-api-cancel-attendance"),
    path("api/monthly/", api_monthly_stats, name="dashboard-api-monthly"),
    path("api/edit-attendance/", api_edit_attendance, name="dashboard-api-edit-attendance"),
    path("api/edit-att/", dashboard_edit_attendance, name="dashboard-api-edit-att"),
    path("api/monthly-goals/", api_monthly_attendance_goals, name="dashboard-api-monthly-goals"),
    path("api/student/<str:student_id>/detail/", api_student_detail, name="dashboard-api-student-detail"),
    path("api/student/<str:student_id>/monthly-attendance/", api_student_monthly_attendance, name="dashboard-api-student-monthly-attendance"),
    path("api/student/<str:student_id>/change-password/", api_change_student_password, name="dashboard-api-change-student-password"),
    path("api/student/<str:student_id>/schedule-delete/", api_schedule_delete, name="dashboard-api-schedule-delete"),
    path("api/student/<str:student_id>/cancel-delete/", api_cancel_delete, name="dashboard-api-cancel-delete"),
    path("api/student/<str:student_id>/confirm-delete/", api_confirm_delete, name="dashboard-api-confirm-delete"),
    path("api/set-location/", api_set_location, name="dashboard-api-set-location"),
    path("api/set-time/", api_set_time, name="dashboard-api-set-time"),
]
