# Generated by Django 4.2.29 on 2026-04-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], max_length=4)),
                ('description', models.TextField(blank=True)),
                ('stages', models.JSONField(default=list)),
            ],
        ),
    ]
