# Generated by Django 4.2.29 on 2026-04-15 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_no', models.PositiveIntegerField(unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('display_slots', models.PositiveSmallIntegerField(default=5)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('total_exp', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('pity_normal', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.PositiveSmallIntegerField(default=0)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('affection', models.PositiveIntegerField(default=0)),
                ('nickname', models.CharField(blank=True, max_length=12, null=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farm.userfarm')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.species')),
            ],
            options={
                'indexes': [models.Index(fields=['farm', '-acquired_at'], name='farm_useran_farm_id_407291_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pet_count', models.PositiveIntegerField(default=0)),
                ('feed_count', models.PositiveIntegerField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='farm.userfarm')),
            ],
            options={
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
