# Generated by Django 4.2.29 on 2026-03-12 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_deadline', models.TimeField(default=datetime.time(10, 0), verbose_name='지각 기준 시간')),
                ('check_out_minimum', models.TimeField(default=datetime.time(18, 0), verbose_name='조퇴 기준 시간')),
            ],
        ),
    ]
