# Generated by Django 4.2.29 on 2026-04-15 08:12

from django.db import migrations, models


def _backfill(apps, schema_editor):
    AR = apps.get_model("attendance", "AttendanceRecord")
    AR.objects.filter(check_out_at__isnull=False).update(reward_granted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_checkoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='reward_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
