# Generated by Django 4.2.29 on 2026-03-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(help_text='URL에 사용될 고유 주소입니다.', max_length=200, unique=True, verbose_name='슬러그')),
                ('summary', models.TextField(blank=True, help_text='목록에 표시될 짧은 설명입니다.', verbose_name='요약')),
                ('content', models.TextField(help_text='마크다운 형식을 지원합니다.', verbose_name='내용')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/', verbose_name='대표 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '블로그 포스트',
                'verbose_name_plural': '블로그 포스트 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
