from django.urls import path

from .views import (
    add_daily_todo,
    add_goal,
    add_goal_from_certification,
    add_lab_goal,
    api_daily_goal,
    api_daily_goal_achieve,
    api_daily_todo_delete,
    api_daily_todo_toggle,
    api_daily_todo_update,
    api_daily_todos,
    api_lab_goals,
    api_weekly_achievement,
    daily_goal_achieve,
    daily_goal_delete,
    daily_goal_save,
    delete_lab_goal,
    delete_daily_todos,
    delete_daily_todo,
    delete_goal,
    register_daily_todos,
    google_calendar_callback,
    google_calendar_connect,
    google_calendar_disconnect,
    google_calendar_import,
    index,
    set_daily_todos_checked,
    toggle_daily_todo,
    toggle_goal,
    update_goal,
)

urlpatterns = [
    path("", index, name="planner-index"),
    path("lab-goals/add/", add_lab_goal, name="planner-lab-goal-add"),
    path("lab-goals/<int:goal_id>/delete/", delete_lab_goal, name="planner-lab-goal-delete"),
    path("google/connect/", google_calendar_connect, name="planner-google-calendar-connect"),
    path("google/callback/", google_calendar_callback, name="planner-google-calendar-callback"),
    path("google/disconnect/", google_calendar_disconnect, name="planner-google-calendar-disconnect"),
    path("google/import/", google_calendar_import, name="planner-google-calendar-import"),
    path("daily-todos/add/", add_daily_todo, name="planner-daily-todo-add"),
    path("daily-todos/set-checked/", set_daily_todos_checked, name="planner-daily-todo-set-checked"),
    path("daily-todos/delete-selected/", delete_daily_todos, name="planner-daily-todo-delete-selected"),
    path("daily-todos/register/", register_daily_todos, name="planner-daily-todo-register"),
    path("daily-todos/<int:todo_id>/toggle/", toggle_daily_todo, name="planner-daily-todo-toggle"),
    path("daily-todos/<int:todo_id>/delete/", delete_daily_todo, name="planner-daily-todo-delete"),
    path("goals/add/", add_goal, name="planner-goal-add"),
    path("goals/add-from-certification/", add_goal_from_certification, name="planner-goal-add-certification"),
    path("goals/<int:goal_id>/delete/", delete_goal, name="planner-goal-delete"),
    path("goals/<int:goal_id>/toggle/", toggle_goal, name="planner-goal-toggle"),
    path("goals/<int:goal_id>/update/", update_goal, name="planner-goal-update"),
    path("api/daily-goal/", api_daily_goal, name="planner-api-daily-goal"),
    path("api/daily-goal/achieve/", api_daily_goal_achieve, name="planner-api-daily-goal-achieve"),
    path("api/weekly-achievement/", api_weekly_achievement, name="planner-api-weekly-achievement"),
    path("daily-goal/save/", daily_goal_save, name="planner-daily-goal-save"),
    path("daily-goal/<int:goal_id>/achieve/", daily_goal_achieve, name="planner-daily-goal-achieve"),
    path("daily-goal/<int:goal_id>/delete/", daily_goal_delete, name="planner-daily-goal-delete"),
    path("api/daily-todos/", api_daily_todos, name="planner-api-daily-todos"),
    path("api/daily-todos/<int:todo_id>/toggle/", api_daily_todo_toggle, name="planner-api-daily-todo-toggle"),
    path("api/daily-todos/<int:todo_id>/update/", api_daily_todo_update, name="planner-api-daily-todo-update"),
    path("api/daily-todos/<int:todo_id>/delete/", api_daily_todo_delete, name="planner-api-daily-todo-delete"),
    path("api/lab-goals/", api_lab_goals, name="planner-api-lab-goals"),
]
