[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/entrypoint.sh"
healthcheckPath = "/api/auth/login/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
