# Generated by Django 4.2.29 on 2026-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='좌석 번호')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='사용 중')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
