# Generated by Django 4.2.29 on 2026-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입실 시간'),
        ),
        migrations.AddField(
            model_name='seat',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='퇴실 시간'),
        ),
    ]
