# Generated by Django 4.2.29 on 2026-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wevity', 'Wevity'), ('dacon', 'Dacon'), ('linkareer', 'Linkareer')], max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255, verbose_name='주최사')),
                ('category', models.CharField(max_length=100, verbose_name='분야')),
                ('reward', models.CharField(blank=True, default='', max_length=100, verbose_name='시상규모')),
                ('content_summary', models.TextField(blank=True, default='', verbose_name='내용 요약')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='태그')),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('deadline_at', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contests_contest',
                'ordering': ['deadline_at', '-created_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='contests_co_source_ecd4ad_idx'), models.Index(fields=['category', 'is_active'], name='contests_co_categor_a07492_idx'), models.Index(fields=['deadline_at'], name='contests_co_deadlin_87c034_idx')],
            },
        ),
    ]
