# Generated by Django 4.2.29 on 2026-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('saramin', 'Saramin'), ('wanted', 'Wanted'), ('crawler', 'Crawler')], max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('job_role', models.CharField(blank=True, default='', max_length=120)),
                ('employment_type', models.CharField(blank=True, default='', max_length=50)),
                ('experience_label', models.CharField(blank=True, default='', max_length=50)),
                ('experience_min', models.PositiveSmallIntegerField(default=0)),
                ('experience_max', models.PositiveSmallIntegerField(default=0)),
                ('education_level', models.CharField(blank=True, default='', max_length=50)),
                ('is_junior_friendly', models.BooleanField(default=False)),
                ('required_skills', models.TextField(blank=True, default='')),
                ('preferred_skills', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='JuniorRequirementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('role', models.CharField(max_length=120)),
                ('skill', models.CharField(max_length=120)),
                ('demand_count', models.PositiveIntegerField(default=0)),
                ('demand_ratio', models.FloatField(default=0.0)),
                ('source_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['stat_date', 'role'], name='planner_jun_stat_da_9158b4_idx'), models.Index(fields=['skill'], name='planner_jun_skill_86748b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='juniorrequirementstat',
            constraint=models.UniqueConstraint(fields=('stat_date', 'role', 'skill'), name='uq_junior_req_stat'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['source', 'external_id'], name='planner_job_source_73cbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_role', 'is_junior_friendly'], name='planner_job_job_rol_4ecf60_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active', 'posted_at'], name='planner_job_is_acti_e8a759_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company_name', 'location'], name='planner_job_company_81ad77_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('source', 'external_id', 'external_url'), name='uq_jobposting_source_external'),
        ),
    ]
