# Generated by Django 4.2.29 on 2026-03-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(help_text="Week start date (Sunday)")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ]
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="weeklygoal",
            index=models.Index(
                fields=["user", "week_start", "weekday"],
                name="planner_wee_user_id_602870_idx",
            ),
        ),
    ]
