# Generated by Django 4.2.29 on 2026-03-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_jobposting_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_key', models.CharField(default='active_jobs', max_length=50, unique=True)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('sampled_job_count', models.PositiveIntegerField(default=0)),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('role_breakdown', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
