# Generated by Django 4.2.29 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_weeklygoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklygoal",
            name="planned_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
