# Generated by Django 4.2.29 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_labwidegoal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklygoal",
            options={"ordering": ["weekday", "planned_time", "created_at"]},
        ),
        migrations.AlterField(
            model_name="weeklygoal",
            name="week_start",
            field=models.DateField(help_text="Week start date (Sunday)"),
        ),
        migrations.AlterField(
            model_name="weeklygoal",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ]
            ),
        ),
    ]
