# Generated by Django 4.2.29 on 2026-03-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_sync_weeklygoal_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weeklygoal',
            new_name='planner_wee_user_id_5ac97b_idx',
            old_name='planner_wee_user_id_602870_idx',
        ),
    ]
