# Generated by Django 4.2.29 on 2026-03-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_rename_planner_wee_user_id_602870_idx_planner_wee_user_id_5ac97b_idx"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField()),
                ("content", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["is_completed", "created_at"]},
        ),
        migrations.AddIndex(
            model_name="dailytodo",
            index=models.Index(
                fields=["user", "target_date", "is_completed"],
                name="planner_dai_user_id_51342d_idx",
            ),
        ),
    ]
