# Generated by Django 4.2.29 on 2026-03-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_dailytodo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailytodo',
            new_name='planner_dai_user_id_2b03b9_idx',
            old_name='planner_dai_user_id_51342d_idx',
        ),
    ]
