# Generated by Django 4.2.29 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_rename_planner_dai_user_id_51342d_idx_planner_dai_user_id_2b03b9_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytodo",
            options={"ordering": ["is_completed", "planned_time", "created_at"]},
        ),
        migrations.AddField(
            model_name="dailytodo",
            name="planned_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
