# Generated by Django 4.2.29 on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_dailytodo_planned_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytodo",
            options={"ordering": ["planned_time", "created_at"]},
        ),
    ]
