# Generated by Django 4.2.29 on 2026-03-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_delete_timetableentry'),
        ('planner', '0003_jobmarketsnapshot'),
        ('planner', '0010_dailytodo_ordering_fix'),
    ]

    operations = [
    ]
