# Generated by Django 4.2.29 on 2026-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_dailytodo_google_event_id_googlecalendarcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygoal',
            name='google_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
