# Generated by Django 4.2.29 on 2026-03-11 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='연구실', max_length=100, verbose_name='위치 이름')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('radius', models.FloatField(default=50.0, verbose_name='허용 반경 (미터)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', '출석'), ('late', '지각'), ('absent', '결석'), ('leave', '조퇴')], default='present', max_length=20)),
                ('check_in_at', models.DateTimeField(auto_now_add=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'attendance_date'], name='attendance__user_id_b34aac_idx')],
                'unique_together': {('user', 'attendance_date')},
            },
        ),
    ]
