# Generated by Django 4.2.29 on 2026-03-11 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='입실 시간')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='퇴실 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '출결 기록',
                'verbose_name_plural': '출결 기록 목록',
                'ordering': ['-date', '-entry_time'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
