# Generated by Django 4.2.29 on 2026-03-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_timetableentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
