# Generated by Django 4.2.29 on 2026-03-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_merge_20260313_1613'),
        ('planner', '0011_merge_20260313_1704'),
    ]

    operations = [
    ]
