# Generated by Django 4.2.29 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_weeklygoal_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytodo',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='red', max_length=10),
        ),
    ]
