# Generated by Django 4.2.29 on 2026-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmarketsnapshot',
            name='analysis_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobmarketsnapshot',
            name='role_breakdown',
            field=models.JSONField(default=list),
        ),
    ]
