# Generated by Django 4.2.29 on 2026-03-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_dailytodo_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytodo',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklygoal',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', max_length=10),
        ),
    ]
